export const SELECT_CHOCOLATE = "SELECT_CHOCOLATE";
export const SET_CART = "SET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";

export const NEXT_STEP = "NEXT_STEP";
export const PREVIOUS_STEP = "PREVIOUS_STEP";
export const ADD_BONBON = "ADD_BONBON";
export const RESET_BONBON = "RESET_BONBON";
export const SET_INDEX = "SET_INDEX";
export const TOGGLE_BONBON_SELECTION = "TOGGLE_BONBON_SELECTION";
export const SET_DIMENSIONS = "SET_DIMENSIONS";
